<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "responsiveimages"
 *
 * Auto generated by Extension Builder 2017-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SCW Responsive Images for FSC',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Joe Schäfer',
	'author_email' => 'joe@joekola.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
			'fluid_styled_responsive_images' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
